### PR TITLE
Create smaller docker images

### PR DESCRIPTION
**Pull request by cas--**
Thanks for this handy docker image however was rather surprised to find it was over 500MB so I refreshed my multi-stage docker skills to clean up the build and bring final size down to 100MB

---

Utilise multi-stage docker builds to reduce size from over 500MB to 100MB

* Base image uses minimal dependencies to run scripts in final stage e.g. only
using node in final CMD means we can move npm to compile stage.
* Reduced dbus-python build dependencies to those actually required.
* Using `pip install --user` to easily copy over Python requirements.
* Bumped Python base image version to 3.10
* Excluded unneeded files from final image.
* Update package-lock.json

### CODE REVIEW

**Comment by cas--** [comment]
I could have shaved another 1.2MB off the node_modules directory with [node_prune](https://github.com/tj/node-prune) but didn't think it was worth chasing that.

**Comment by cas--** [comment]
Image doesn't seem to be working on my server so need to investigate further :thinking:

**Comment by hardillb** [comment]
Sorry it took a while, just remembered this.

**Comment by hardillb** [comment]
Hmm, this failed on the arm7 (32bit) build. Will investigate

**Comment by hardillb** [comment]
Fixed

**Pull request merged**
